# Generated by Django 5.2.12 on 2026-04-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriptionplan_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='name',
        ),
    ]
