# Generated by Django 5.2.12 on 2026-04-10 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subscriptionplan_name"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="user",
        #     name="id",
        #     field=models.UUIDField(
        #         default=uuid.uuid4, editable=False, primary_key=True, serialize=False
        #     ),
        # ),
    ]
