# Generated by Django 5.2.12 on 2026-04-10 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_id"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='temp_id',
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='tempid',
        #     field=models.CharField(default=1, editable=False, max_length=100),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
    ]
