# Generated by Django 5.2.12 on 2026-04-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_temp_id_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slug',
            new_name='path',
        ),
    ]
