# Generated by Django 5.2.12 on 2026-04-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_slug_user_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='path',
            new_name='uuid_slug',
        ),
    ]
