# Generated by Django 5.2.12 on 2026-04-10 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_path_user_uuid_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='uuid_slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
