# Generated by Django 5.2.12 on 2026-04-10 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('rose', 'Rose'), ('amber', 'Amber'), ('teal', 'Teal'), ('indigo', 'Indigo'), ('orange', 'Orange'), ('cyan', 'Cyan'), ('pink', 'Pink'), ('emerald', 'Emerald')], max_length=20)),
                ('access', models.CharField(choices=[('public', 'Public'), ('premium', 'Premium')], default='public', max_length=10)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(blank=True, default='', upload_to='avatars/')),
                ('role', models.CharField(default='', max_length=200)),
                ('twitter', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=600, unique=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField(default='')),
                ('excerpt', models.CharField(default='', max_length=500)),
                ('cover_image', models.ImageField(blank=True, default='', upload_to='articles/')),
                ('cover_caption', models.CharField(blank=True, default='', max_length=500)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('feature', 'Feature'), ('opinion', 'Opinion'), ('brief', 'Brief'), ('explainer', 'Explainer'), ('interview', 'Interview')], default='article', max_length=20)),
                ('access', models.CharField(choices=[('public', 'Public'), ('premium', 'Premium')], default='public', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], default='draft', max_length=20)),
                ('seo_title', models.CharField(blank=True, default='', max_length=500)),
                ('seo_description', models.CharField(blank=True, default='', max_length=1000)),
                ('seo_keywords', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading_time', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='common.author')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to='common.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='common.category')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('cover_image', models.ImageField(blank=True, default='', upload_to='editions/')),
                ('status', models.CharField(choices=[('published', 'Published'), ('scheduled', 'Scheduled'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('print_ready', models.BooleanField(default=False)),
                ('print_pdf_url', models.FileField(blank=True, default='', upload_to='editions/pdfs/')),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in', to='common.article')),
            ],
            options={
                'db_table': 'editions',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='editions',
            field=models.ManyToManyField(blank=True, related_name='articles', to='common.edition'),
        ),
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shipping_region', models.CharField(choices=[('us', 'US'), ('international', 'International')], default='us', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=20)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.edition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'print_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='idx_articles_slug'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='idx_articles_category'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author'], name='idx_articles_author'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='idx_articles_published'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='idx_articles_status'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['access'], name='idx_articles_access'),
        ),
    ]
