# Generated by Django 5.2.12 on 2026-04-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_category_author_article_edition_article_editions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
