# Generated by Django 5.2.12 on 2026-04-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_article_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='printorder',
            name='payment_id',
            field=models.CharField(blank=True, default='', help_text='External payment reference', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='content_config',
            field=models.JSONField(default=dict, help_text='{"require_editor_approval": true, "auto_moderate": false, "banned_words": [], "max_article_word_count": 10000}'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_flags',
            field=models.JSONField(default=dict, help_text='{"subscriptions_enabled": true, "print_orders_enabled": true, "comments_enabled": false, "social_auth_enabled": false, "otp_via_sms_enabled": false}'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pricing_config',
            field=models.JSONField(default=dict, help_text='{"subscription_plans": {"currency": "USD"}, "print": {"us": {"unit": "12.99", "shipping": "4.99"}, "international": {"unit": "14.99", "shipping": "12.99"}, "bulk_threshold": 5, "bulk_discount_percent": "10.0"}}'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rate_limit_config',
            field=models.JSONField(default=dict, help_text='{"login": {"max_attempts": 5, "window_seconds": 60}, "register": {"max_attempts": 3, "window_seconds": 3600}, "api": {"max_requests": 100, "window_seconds": 60}, "otp": {"max_attempts": 5, "window_seconds": 300}}'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='security_config',
            field=models.JSONField(default=dict, help_text='{"admin_allowed_ips": [], "allowed_countries": [], "token_lifetime_days": 7, "password_min_length": 8}'),
        ),
    ]
