# Generated by Django 5.2.12 on 2026-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_printorder_payment_id_sitesettings_content_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_config',
            field=models.JSONField(default=dict, help_text='{"name": "MERIDIAN", "tagline": "...", "description": "...", "url": "...", "terms_of_service_url": "/terms", "nav_links": [...], "footer_links": [...], "social_links": [...], "payment_gateways": [...]}'),
        ),
    ]
